<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro">
    <!-- 1. 常量定义（方便后续修改尺寸） -->
    <xacro:property name="base_length" value="0.4" />
    <xacro:property name="base_height" value="0.1" />
    <xacro:property name="link_length" value="0.3" />
    <xacro:property name="link_radius" value="0.03" />

    <link name="map">
        <origin xyz="0 0 0" rpy="0 0 0" />
    </link>

    <joint name="map_joint" type="fixed">
        <parent link="map" />
        <child link="base_link" />
        <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>

    <!-- 2.1 底座连杆（base_link） -->
    <link name="base_link">
        <visual>
            <origin xyz="0 0 ${base_height/2}" rpy="0 0 0" />
            <geometry>
                <box size="${base_length} ${base_length} ${base_height}" />
            </geometry>
            <material name="gray">
                <color rgba="0.5 0.5 0.5 1" />
            </material>
        </visual>
    </link>
    <link name="link1">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder length="${link_length}" radius="${link_radius}" />
            </geometry>
            <material name="red">
                <color rgba="1.0 0.0 0.0 1.0" />
            </material>
        </visual>
    </link>
    <joint name="base_to_link1_joint" type="revolute">
        <parent link="base_link" />
        <child link="link1" />
        <origin xyz="0 0 ${base_height}" rpy="0 0 0" />
        <axis xyz="0 0 1" />
        <limit effort="100" velocity="1" lower="${-1*pi}" upper="${pi}" />
    </joint>



</robot>